#ifndef BRUHMOMENT_H
#define BRUHMOMENT_H

#define yeet throw
#define fax bool
#define squad class
#define lit const
#define solid const
#define delete_dota_ty delete
#define cancel delete
#define nah else
#define hustle for
#define vibe_check if
#define is_sus if
#define numba int
#define schlong long
#define prepare_for_trouble float
#define and_make_it_double double
#define thicc new
#define ggez return
#define sizeup sizeof
#define castle struct
#define slay switch
#define situationship case
#define templatez template
#define streetz_name typedef
#define my_soul void
#define go_brrr while
#define fuck_around try
#define find_out catch
#define bussin continue
#define no_cap true
#define cap false
#define basic default
#define vibe_out do
#define attacc goto
#define flex auto
#define lowkey private
#define highkey public
#define protecc protected
#define bro friend
#define nuthin nullptr
#define swag unsigned
#define dis this
#define chillax break
#define hype inline
#define short_king short
#define yolo signed
#define npc static
#define meta virtual
#define xoxo xor
#define poggers reinterpret_cast
#define fire static_cast
#define spill_tea cout
#define yo_listen cin
#define let_them_cook await
#define ick exception
#define yasss using
#define queen namespace
#define goat 1
#define shade 0
#define period return 0
#define to_me <<
#define to_you >>
#define more_rizz_than >
#define less_rizz_than <
#define mood =
#define me_too ==
#define moar ++
#define slap << "\n"
#define deez_nutz this
#define numba_deez enum

#endif // BRUHMOMENT_H
